# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "li huating"                                # Your name
  description: "A normal student"  
  image: img/profile.png
  
  favicon: /img/1.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/tianzhong.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd

    # your social media handles
    right:
    - icon: github
      text: Github
      href: https://github.com/lht121/LHT1218
    - icon: envelope
      text: Email
      href: "mailto:mail.1536597717@qq.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Marvin Schmitt CC BY-SA 4.0</span>
    center: |
      <span class="faux-block"><a href="www.lihuatting.com/blog/homework/">View the tutorial for this template!</a></span>
    right: |
      <span class="faux-block"><a href="https://github.com/lht121/LHT1218">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 2222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true